services:
  web:
    build: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: src/fastapi_demo/.
          target: /home/dev
  redis:
    image: "redis:alpine"